### ISSUE TITLE
Delete before write fails

### ISSUE THREAD

**Issue by jeluard** [sbtourist/Journal.IO#23]
When deleting a Location before doing any write throws following exception:

``` java
Exception in thread "main" java.lang.IllegalStateException
    at journal.io.api.Journal.sync(Journal.java:270)
    at journal.io.api.DataFileAccessor.updateLocation(DataFileAccessor.java:60)
    at journal.io.api.Journal.delete(Journal.java:337)
    at com.github.jeluard.stone.DeleteBeforeWrite.main(DeleteBeforeWrite.java:16)
Caused by: java.lang.NullPointerException
    at journal.io.api.Journal$WriteFuture.get(Journal.java:1009)
    at journal.io.api.Journal$WriteFuture.get(Journal.java:988)
    at journal.io.api.Journal.sync(Journal.java:265)
    ... 3 more
```

Same code but with a write forced before the delete runs fine.

**Comment by jeluard** [comment]
You can find an example [here](https://gist.github.com/4596695). Note you need to have a file names `test1.log` in the directory used to run the example.

**Comment by sbtourist** [comment]
Fixed.
